all: installed

GIT_DIR = libfreenect
GIT_URL = git://github.com/ros-pkg-git/libfreenect.git
#GIT_PATCH = 
GIT_REVISION=ros

include $(shell rospack find mk)/git_checkout.mk


.PHONY: build


installed: preclean $(GIT_DIR)
	touch installed

preclean: Makefile.libfreenect
	make -f Makefile.libfreenect preclean
	touch preclean

clean:
	rm -f installed
	rm -fr lib include
	-make -C $(GIT_DIR) clean

preclean: clean
	-rm -rf $(GIT_DIR) 

wipe: clean
	-rm -rf build
	-rm -rf $(GIT_DIR) 
